In [2]:
# import various libraries/directories used for knn machine learning
#imported under diffrent names for ease of coding
import pandas as pd
#use of numpy - a library used for working with arrays
import numpy as np
#various sklearn subdirectories which will be used for performing the knn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score
from sklearn import preprocessing

In [3]:
#define the 'data' variable as the car.csv file
#the car.csv files has 7 columns, which relate to specific charectistics of cars
data = pd.read_csv("car.data")

#print the first 5 rows of the data variable, which is the car.csv file
print(data.head())

  buying  maint doors persons lug_boot safety  class
0  vhigh  vhigh     2       2    small    low  unacc
1  vhigh  vhigh     2       2    small    med  unacc
2  vhigh  vhigh     2       2    small   high  unacc
3  vhigh  vhigh     2       2      med    low  unacc
4  vhigh  vhigh     2       2      med    med  unacc


In [4]:
#convert all categorical variables into numbers using label encoder
#this allows for the use of categorical data even when some machine learning models dont allow for the use of categorical data.

#define the 'label_encoder' variable as the lable encoder function
label_encoder = preprocessing.LabelEncoder() 

#replace the specified colums with their label encoded (numerical) counterparts so that they can be used in machine learning
data['buying']= label_encoder.fit_transform(data['buying']) 
data['maint']= label_encoder.fit_transform(data['maint']) 
data['lug_boot']= label_encoder.fit_transform(data['lug_boot']) 
data['safety']= label_encoder.fit_transform(data['safety']) 
data['class']= label_encoder.fit_transform(data['class']) 

#these columns use both numerical and categorical data, so the 'replace' method is used
#replace the data with numerical (and ordered) values
data['doors'].replace(['2', '3', '4', '5more'], [0, 1, 2, 3], inplace=True)
data['persons'].replace(['2', '4', 'more'], [0, 1, 2], inplace=True)

#print data to check if replacement has worked
  
print(data)

      buying  maint  doors  persons  lug_boot  safety  class
0          3      3      0        0         2       1      2
1          3      3      0        0         2       2      2
2          3      3      0        0         2       0      2
3          3      3      0        0         1       1      2
4          3      3      0        0         1       2      2
...      ...    ...    ...      ...       ...     ...    ...
1723       1      1      3        2         1       2      1
1724       1      1      3        2         1       0      3
1725       1      1      3        2         0       1      2
1726       1      1      3        2         0       2      1
1727       1      1      3        2         0       0      3

[1728 rows x 7 columns]


In [5]:
#assign the x and y variables as just the first 6 colums, as we want to predict the 7th column, so dont want it in the data.
x = data.iloc[:, 0:6]
y = data.iloc[:, 6] 
#split the data into the test and train. The test_size 0.2 indicateds that 20% of the data will be sued for test
# this means that 80% will be used to train
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=0, test_size=0.2)

In [6]:
#standardise the training sets to make for easier use of the data sets in KNN
sc_x = StandardScaler()
x_train = sc_x.fit_transform(x_train)
x_test = sc_x.transform(x_test)

In [7]:
#import the math library
import math

#tells how many values there are in the y_test
print(len(y_test))
#find the sqaure root of the number of values in y_test
math.sqrt(len(y_test))

346


18.601075237738275

In [8]:
#define the number of neighbours used for the KNN
#also defines the metric of calculation of the distance to points
# in this case, euclidian (uses the eucledian distance)
classifier = KNeighborsClassifier(n_neighbors=6, p=2, metric='euclidean')
classifier.fit(x_train, y_train)

KNeighborsClassifier(metric='euclidean', n_neighbors=6)

In [9]:
y_pred = classifier.predict(x_test)
y_pred

array([2, 2, 2, 2, 2, 0, 2, 0, 0, 2, 2, 2, 0, 2, 2, 0, 2, 2, 0, 2, 0, 0,
       0, 2, 2, 2, 2, 2, 2, 2, 0, 0, 2, 0, 0, 2, 2, 2, 2, 0, 2, 2, 2, 2,
       3, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 2, 2, 2, 0, 0,
       2, 0, 2, 2, 2, 0, 0, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0, 0, 2, 2, 2, 0,
       2, 2, 2, 0, 0, 2, 2, 3, 2, 0, 0, 2, 2, 0, 0, 2, 3, 0, 2, 0, 2, 2,
       2, 2, 2, 0, 2, 1, 0, 2, 2, 2, 2, 2, 0, 0, 2, 2, 2, 0, 1, 2, 2, 2,
       0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 0, 2, 2, 0, 0, 0, 2, 2,
       2, 0, 2, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2,
       2, 2, 2, 2, 0, 0, 0, 2, 0, 2, 1, 2, 2, 2, 2, 0, 2, 2, 2, 0, 2, 0,
       2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 0, 2, 2,
       2, 0, 2, 3, 2, 2, 2, 3, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 0, 2, 0, 2, 2, 2, 2, 2, 1, 0, 0, 0, 0, 2, 2, 2, 0, 2, 2, 0,
       2, 2, 3, 2, 0, 2, 2, 2, 0, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0,
       2, 3, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2,

In [10]:
#print out the confusion matrix - a number that shows the accuracy of a machine learning model
#the higher the confusion matrix, the higher the accuracy of the classification using KNN.
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(accuracy_score(y_test, y_pred))

[[ 76   0   3   0]
 [  8   9   0   0]
 [  8   0 232   0]
 [  1   0   0   9]]
0.9421965317919075
